variable "veda" {}
variable "storage01" {}
variable "ranjeet" {}
variable "virtule_net1" {}
variable "veda_subnet" {}
variable "veda_vm" {}
variable "veda-db" {}
variable "veda_key" {}
variable "veda_host" {}
